cities = ['BANDA ACEH',
          'LANGSA',
          'LHOKSEUMAWE',
          'MEULABOH',
          'SABANG',
          'SUBULUSSALAM',
          'DENPASAR',
          'PANGKALPINANG',
          'CILEGON',
          'SERANG',
          'TANGERANG',
          'BENGKULU',
          'GORONTALO',
          'JAKARTA',
          'SUNGAI PENUH',
          'JAMBI',
          'BANDUNG',
          'BEKASI',
          'BOGOR',
          'CIMAHI',
          'CIREBON',
          'DEPOK',
          'SUKABUMI',
          'TASIKMALAYA',
          'BANJAR',
          'MAGELANG',
          'PEKALONGAN',
          'PURWOKERTO',
          'SALATIGA',
          'SEMARANG',
          'SURAKARTA',
          'TEGAL',
          'BATU',
          'BLITAR',
          'KEDIRI',
          'MADIUN',
          'MALANG',
          'MOJOKERTO',
          'PASURUAN',
          'PROBOLINGGO',
          'SURABAYA',
          'PONTIANAK',
          'SINGKAWANG',
          'BANJARBARU',
          'BANJARMASIN',
          'PALANGKARAYA',
          'BALIKPAPAN',
          'BONTANG',
          'SAMARINDA',
          'TARAKAN',
          'BATAM',
          'TANJUNGPINANG',
          'BANDAR LAMPUNG',
          'METRO',
          'TERNATE',
          'TIDORE KEPULAUAN',
          'AMBON',
          'TUAL',
          'BIMA',
          'MATARAM',
          'KUPANG',
          'SORONG',
          'JAYAPURA',
          'DUMAI',
          'PEKANBARU',
          'MAKASSAR',
          'PALOPO',
          'PAREPARE',
          'PALU',
          'BAU-BAU',
          'KENDARI',
          'BITUNG',
          'KOTAMOBAGU',
          'MANADO',
          'TOMOHON',
          'BUKITTINGGI',
          'PADANG',
          'PADANGPANJANG',
          'PARIAMAN',
          'PAYAKUMBUH',
          'SAWAHLUNTO',
          'SOLO'
          'SOLOK',
          'LUBUKLINGGAU',
          'PAGARALAM',
          'PALEMBANG',
          'PRABUMULIH',
          'BINJAI',
          'MEDAN',
          'PADANG SIDEMPUAN',
          'PEMATANGSIANTAR',
          'SIBOLGA',
          'TANJUNGBALAI',
          'TEBINGTINGGI',
          'YOGYAKARTA'
          ]

regencies = ["ACEH",
             "AGAM",
             "ALOR",
             "ASAHAN",
             "ASMAT",
             "BADUNG",
             "BALANGAN",
             "BANDUNG",
             "BANGGAI",
             "BANGKA",
             "BANGKALAN",
             "BANGLI",
             "BANJAR",
             "BANJARNEGARA",
             "BANTAENG",
             "BANTUL",
             "BANYUASIN",
             "BANYUMAS",
             "BANYUWANGI",
             "BARITO KUALA",
             "BARRU",
             "BATANG",
             "BATANGHARI",
             "BATUBARA",
             "BEKASI",
             "BELITUNG",
             "BELU",
             "BENER MERIAH",
             "BENGKALIS",
             "BENGKAYANG",
             "BENGKULU",
             "BERAU",
             "BIAK NUMFOR",
             "BIMA",
             "BINTAN",
             "BIREUEN",
             "BLITAR",
             "BLORA",
             "BOALEMO",
             "BOGOR",
             "BOJONEGORO",
             "BOLAANG MONGONDOW",
             "BOMBANA",
             "BONDOWOSO",
             "BONE BOLANGO",
             "BONE",
             "BOVEN DIGOEL",
             "BOYOLALI",
             "BREBES",
             "BULELENG",
             "BULUKUMBA",
             "BULUNGAN",
             "BUNGO",
             "BUOL",
             "BURU",
             "BUTON",
             "CIAMIS",
             "CIANJUR",
             "CILACAP",
             "CIREBON",
             "DAIRI",
             "DEIYAI",
             "DELI SERDANG",
             "DEMAK",
             "DHARMASRAYA",
             "DOGIYAI",
             "DOMPU",
             "DONGGALA",
             "EMPAT LAWANG",
             "ENDE",
             "ENREKANG",
             "FAKFAK",
             "FLORES",
             "GARUT",
             "GAYO LUES",
             "GIANYAR",
             "GORONTALO",
             "GOWA",
             "GRESIK",
             "GROBOGAN",
             "GUNUNG KIDUL",
             "GUNUNG MAS",
             "HALMAHERA",
             "HULU SUNGAI",
             "HUMBANG HASUNDUTAN",
             "INDRAGIRI HILIR",
             "INDRAGIRI HULU",
             "INDRAMAYU",
             "INTAN JAYA",
             "JAYAPURA",
             "JAYAWIJAYA",
             "JEMBER",
             "JEMBRANA",
             "JENEPONTO",
             "JEPARA",
             "JOMBANG",
             "KAIMANA",
             "KAMPAR",
             "KAPUAS HULU",
             "KAPUAS",
             "KARANGANYAR",
             "KARANGASEM",
             "KARAWANG",
             "KARIMUN",
             "KARO",
             "KATINGAN",
             "KAUR",
             "KAYONG",
             "KEBUMEN",
             "KEDIRI",
             "KEEROM",
             "KENDAL",
             "KEPAHIANG",
             "KEPULAUAN ANAMBAS",
             "KEPULAUAN ARU",
             "KEPULAUAN MENTAWAI",
             "KEPULAUAN MERANTI",
             "KEPULAUAN SANGIHE",
             "KEPULAUAN SELAYAR",
             "KEPULAUAN SERIBU",
             "KEPULAUAN SIAU TAGULANDANG BIARO",
             "KEPULAUAN SULA",
             "KEPULAUAN TALAUD",
             "KEPULAUAN YAPEN",
             "KERINCI",
             "KETAPANG",
             "KLATEN",
             "KLUNGKUNG",
             "KOLAKA",
             "KONAWE KEPULAUAN",
             "KONAWE",
             "KOTABARU",
             "KOTAWARINGIN",
             "KUANTAN SINGINGI",
             "KUBU RAYA",
             "KUDUS",
             "KULON PROGO",
             "KUNINGAN",
             "KUPANG",
             "KUTAI",
             "KUTAI KARTANEGARA",
             "LABUHANBATU",
             "LAHAT",
             "LAMANDAU",
             "LAMONGAN",
             "LAMPUNG",
             "LANDAK",
             "LANGKAT",
             "LANNY JAYA",
             "LEBAK",
             "LEBONG",
             "LEMBATA",
             "LIMA PULUH KOTA",
             "LINGGA",
             "LOMBOK",
             "LUMAJANG",
             "LUWU",
             "MADIUN",
             "MAGELANG",
             "MAGETAN",
             "MAHAKAM ULU",
             "MAJALENGKA",
             "MAJENE",
             "MALAKA",
             "MALANG",
             "MALINAU",
             "MALUKU",
             "MAMASA",
             "MAMBERAMO RAYA",
             "MAMBERAMO",
             "MAMUJU",
             "MANDAILING NATAL",
             "MANGGARAI",
             "MANOKWARI",
             "MAPPI",
             "MAROS",
             "MAYBRAT",
             "MELAWI",
             "MERANGIN",
             "MERAUKE",
             "MESUJI",
             "MIMIKA",
             "MINAHASA",
             "MOJOKERTO",
             "MOROWALI",
             "MUARA ENIM",
             "MUARO JAMBI",
             "MUKOMUKO",
             "MUNA",
             "MURUNG RAYA",
             "MUSI BANYUASIN",
             "MUSI RAWAS",
             "NABIRE",
             "NAGAN RAYA",
             "NAGEKEO",
             "NATUNA",
             "NDUGA",
             "NGADA",
             "NGANJUK",
             "NGAWI",
             "NIAS",
             "NUNUKAN",
             "OGAN ILIR",
             "OGAN ULU",
             "PACITAN",
             "PADANG LAWAS",
             "PADANG PARIAMAN",
             "PAKPAK",
             "PAMEKASAN",
             "PANDEGLANG",
             "PANGANDARAN",
             "PANGKAJENE DAN KEPULAUAN",
             "PANIAI",
             "PARIGI MOUTONG",
             "PASAMAN",
             "PASER",
             "PASURUAN",
             "PATI",
             "PEGUNUNGAN ARFAK",
             "PEGUNUNGAN BINTANG",
             "PEKALONGAN",
             "PELALAWAN",
             "PEMALANG",
             "PENAJAM PASER",
             "PENUKAL ABAB LEMATANG ILIR",
             "PESAWARAN",
             "PESISIR",
             "PIDIE JAYA",
             "PIDIE",
             "PINRANG",
             "POHUWATO",
             "POLEWALI MANDAR",
             "PONOROGO",
             "MEMPAWAH",
             "POSO",
             "PRINGSEWU",
             "PROBOLINGGO",
             "PULANG PISAU",
             "PULAU MOROTAI",
             "PULAU TALIABU",
             "PUNCAK JAYA",
             "PUNCAK",
             "PURBALINGGA",
             "PURWAKARTA",
             "PURWOREJO",
             "RAJA AMPAT",
             "REJANG LEBONG",
             "REMBANG",
             "ROKAN HILIR",
             "ROKAN HULU",
             "ROTE NDAO",
             "SABU RAIJUA",
             "SAMBAS",
             "SAMOSIR",
             "SAMPANG",
             "SANGGAU",
             "SARMI",
             "SAROLANGUN",
             "SEKADAU",
             "SELUMA",
             "SEMARANG",
             "SERAM BAGIAN",
             "SERANG",
             "SERDANG BEDAGAI",
             "SERUYAN",
             "SIAK",
             "SIDENRENG RAPPANG",
             "SIDOARJO",
             "SIGI",
             "SIJUNJUNG",
             "SIKKA",
             "SIMALUNGUN",
             "SIMEULUE",
             "SINJAI",
             "SINTANG",
             "SITUBONDO",
             "SLEMAN",
             'SOLO',
             "SOLOK",
             "SOPPENG",
             "SORONG",
             "SRAGEN",
             "SUBANG",
             "SUKABUMI",
             "SUKAMARA",
             "SUKOHARJO",
             "SUMBA",
             "SUMBAWA",
             "SUMEDANG",
             "SUMENEP",
             "SUPIORI",
             "TABALONG",
             "TABANAN",
             "TAKALAR",
             "TAMBRAUW",
             "TANA TIDUNG",
             "TANA TORAJA",
             "TANAH BUMBU",
             "TANAH DATAR",
             "TANAH LAUT",
             "TANGERANG",
             "TANGGAMUS",
             "TANJUNG JABUNG",
             "TAPANULI",
             "TAPIN",
             "TASIKMALAYA",
             "TEBO",
             "TEGAL",
             "TELUK BINTUNI",
             "TELUK WONDAMA",
             "TEMANGGUNG",
             "TIMOR",
             "TOBA SAMOSIR",
             "TOJO UNA-UNA",
             "TOLI-TOLI",
             "TOLIKARA",
             "TORAJA",
             "TRENGGALEK",
             "TUBAN",
             "TULANG BAWANG",
             "TULUNGAGUNG",
             "WAJO",
             "WAKATOBI",
             "WAROPEN",
             "WAY KANAN",
             "WONOGIRI",
             "WONOSOBO",
             "YAHUKIMO",
             "YALIMO"]
